### ISSUE TITLE
Can load nativeBLAS but have link error

### ISSUE THREAD

**Issue by pop088** [fommil/netlib-java#108]
Hi, I am running a piece of my code including

`import com.github.fommil.netlib.BLAS;
 System.out.println(BLAS.getInstance().getClass().getName());`

This outputs normally
`com.github.fommil.netlib.NativeSystemBLAS `

However, when my code comes to calculation parts, I got this error.

`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.github.fommil.netlib.NativeSystemBLAS.sgemm_offsets(Ljava/lang/String;Ljava/lang/String;IIIF[FII[FIIF[FII)V
        at com.github.fommil.netlib.NativeSystemBLAS.sgemm_offsets(Native Method)
        at com.github.fommil.netlib.NativeSystemBLAS.sgemm(NativeSystemBLAS.java:451)
        at org.nd4j.linalg.cpu.blas.CpuLevel3.sgemm(CpuLevel3.java:34)
        at org.nd4j.linalg.api.blas.impl.BaseLevel3.gemm(BaseLevel3.java:57)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2537)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2343)
`

I suppose it's a link problem, but I has already loaded the NativeSystemBLAS successfully?

Thanks a lot.

**Comment by fommil** [comment]
Hi, sorry I only answer support questions about netlib-java under a commercial contract. This is not a bug
